//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeBook.Data.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OfficeBookEFEntities : DbContext
    {
        public OfficeBookEFEntities()
            : base("name=OfficeBookEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ob_announcements> ob_announcements { get; set; }
        public DbSet<ob_attachments> ob_attachments { get; set; }
        public DbSet<ob_comments> ob_comments { get; set; }
        public DbSet<ob_files> ob_files { get; set; }
        public DbSet<ob_groupfiles> ob_groupfiles { get; set; }
        public DbSet<ob_groupposts> ob_groupposts { get; set; }
        public DbSet<ob_groups> ob_groups { get; set; }
        public DbSet<ob_groupusers> ob_groupusers { get; set; }
        public DbSet<ob_postattachments> ob_postattachments { get; set; }
        public DbSet<ob_postcomments> ob_postcomments { get; set; }
        public DbSet<ob_postfiles> ob_postfiles { get; set; }
        public DbSet<ob_postreactions> ob_postreactions { get; set; }
        public DbSet<ob_posts> ob_posts { get; set; }
        public DbSet<ob_reactions> ob_reactions { get; set; }
        public DbSet<ob_tasks> ob_tasks { get; set; }
        public DbSet<ob_typesof_files> ob_typesof_files { get; set; }
        public DbSet<ob_typesof_posts> ob_typesof_posts { get; set; }
        public DbSet<ob_typesof_reactions> ob_typesof_reactions { get; set; }
        public DbSet<ob_usercomments> ob_usercomments { get; set; }
        public DbSet<ob_userfiles> ob_userfiles { get; set; }
        public DbSet<ob_userposts> ob_userposts { get; set; }
        public DbSet<ob_userreactions> ob_userreactions { get; set; }
        public DbSet<ob_users> ob_users { get; set; }
    }
}
